# Generated by Django 4.2.11 on 2026-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedGame',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cached_at'],
            },
        ),
    ]
