# Generated by Django 4.2.11 on 2026-04-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedgame',
            name='full_steam_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
