# Generated by Django 4.2.11 on 2026-05-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_dailychallenge"),
    ]

    operations = [
        migrations.CreateModel(
            name="SteamSpyTopGameList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=64, unique=True),
                ),
                ("app_ids", models.JSONField(default=list)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
