# Generated by Django 4.2.11 on 2026-05-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_steamspytopgamelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedGame',
        ),
    ]
