name = "steam-guesser"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-26"

[env.production]

[[d1_databases]]
binding = "steam_apps_db"
database_name = "steam-apps-db"
database_id = "2d8e83ec-4b46-4f04-a486-525fc43df151"
