name = "steam-db-updater"
main = "src/index.js"
compatibility_date = "2026-05-29"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = ["* * * * *", "0 0 * * *"]

[[d1_databases]]
binding = "steam_apps_db"
database_name = "steam-apps-db"
database_id = "2d8e83ec-4b46-4f04-a486-525fc43df151"

[vars]
# === api rate limits ===
BATCH_SIZE = 5   # one batch processed each minute
REQUEST_DELAY = 1500   # delay between fetches of each game

# === database restrictions ===
REVIEWS_PER_GAME = 5
ACHIEVEMENTS_PER_GAME = 10
